### ISSUE TITLE
Version checker not updating

### ISSUE THREAD

**Issue by Pulseeey** [Flexget/webui#100]
Hi,

The version checker doesn't seem to be updated with my current version, any ideas?

root@Flexget:~/flexget# flexget -V
3.1.46
You are on the latest release.

The Web GUI still shows me this though:
Version info
Flexget: 3.0.28  
API: 1.7.0

Not sure how to reset it, or how it's checking it.

Thanks.

**Comment by paranoidi** [comment]
Have you restarted the daemon?

**Comment by Pulseeey** [comment]
> Have you restarted the daemon?

Yes, everything has been restarted including the actual VM. The log shows it check it seems but it shows something along the lines of "version already exist in database 3.0.38".

Anyway for me to replicate the way it's getting the version? I've even tried reinstalling flexget entirely and copying over my config and db (I'd rather not lose progress) and it still shown that version.

**Comment by paranoidi** [comment]
Sounds like UI shows the version incorrectly.

**Comment by kristenmills** [comment]
I'm going to close this. If this is still an issue, please reopen
