### ISSUE TITLE
Unable to execute newly created task

### ISSUE THREAD

**Issue by peterox** [Flexget/webui#114]
### Expected behaviour:
- Author a new task in the config page
- Goto task page
- Click Execute button
- Find the newly authored task in the list

### Actual behaviour:
The newly authored task does not appear in the list.

It seems the tasks to choose from are sourced from the list of tasks displayed inn the page, so any new tasks are not selectable and there is no way to just enter any task.

### Steps to reproduce:
- See above

#### Config:
```yaml
Paste FULL config and remove any personal info if config is too long, attach the file to the ticket.
If issue is with a single task, you can get get resulting configuration by running:
  flexget execute --task <NAME> --dump-config
Make sure to redact any personal information (passwords, api keys, etc) !
```

#### Log:
<details>
 <summary>(click to expand)</summary>

```
paste log output here
```
</details>

### Additional information:

- FlexGet version: 3.1.56
- Installation method: Docker
- OS and version: QNAP
- Browser Verson: Chrome latest

**Comment by kristenmills** [comment]
Thanks for the bug report. Getting a PR to fix it up right now.

**Comment by kristenmills** [comment]
Will be fixed in the next flexget release
