### ISSUE TITLE
The server could not verify that you are authorized to access the URL requested.

### ISSUE THREAD

**Issue by FeromonDE** [Flexget/webui#120]
After login i get a error

The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.

Password is set and is right. I can login in. But every time i see a error.

Flexget 3.1.66

Firefox Console

{"username":"flexget","password":"xxxxxxxxx*"}

{
  "message": "user logged in", 
  "status": "success", 
  "status_code": 200
}

**Comment by kristenmills** [comment]
@FeromonDE Should be fixed in the next release
