### ISSUE TITLE
[BUG] Reversed Season\Episode identifiers

### ISSUE THREAD

**Issue by BrutuZ** [Flexget/webui#76]
### Expected behaviour:
Episode 08 of Season 01 to be shown as S01E08
### Actual behaviour:
Episode 08 of Season 01 is shown as S08E01 (visual only)
### Steps to reproduce:
- Step 1: Just visited a series page (`/series/<id>`)

#### Screenshots:
I hid the thumbnails to fit more than 3 cards on the screenshot
![Screenshot](https://i.imgur.com/bhP5HMb.png)

### Additional information:

- FlexGet version: 3.1.1
- Python version: 3.7
- Installation method: Git
- OS and version: Win 10

**Comment by liiight** [comment]
Hmm, can you run `flexget series show "Infinity train"`

**Comment by BrutuZ** [comment]
I did before opening the issue, they are assigned correctly in the DB just a visual issue on WebUI v2 card titles. Episode descriptions, thumbnails, and matched entries are all correct so it should be something silly simple like reversed variables on the Card Title template :)

**Comment by kristenmills** [comment]
Yeah it's a webui bug. I swapped it accidently but only for tvmaze which is probably why it's not seen by everyone. 
https://github.com/Flexget/webui/blob/225bfaa708c7df14f772e40b3b9b6e43fa0b3e03/src/core/entry/lookup/episodes.ts#L100

will fix. Thanks for reporting
