### ISSUE TITLE
Tasks execution

### ISSUE THREAD

**Issue by RicardoVelaC** [Flexget/webui#84]
### Expected behaviour: 
Add ability to execute one specific task on demand, like old WebUI v1

### Actual behaviour: 
In new WebUI v2 you can't execute an specific task

### Additional information:

- FlexGet version: 3.1.8
- API version 1.7.1
- Installation method: Docker
- OS and version: Linux-Alpine
- Browser Version: Chrome 79

**Comment by kristenmills** [comment]
It’s Being worked on here: https://github.com/Flexget/webui/pull/83

**Comment by kristenmills** [comment]
Fixed in #83
